export PYTHON=python
export PYTHONPATH+=$(shell ${PYTHON} ./scripts/testpath.py)

all: clean build test


build:
	@${PYTHON} setup.py build

test:
	@${PYTHON} test_rbtree.py

install:
	@${PYTHON} setup.py install

dist:
	@${PYTHON} setup.py bdist

clean:
	@find . -name "*.pyc" -exec rm {} \;
	@find . -name "*~" -exec rm {} \;
	@rm -f src/rbtree.c # generated by pyrex
	@rm -rf build
	@rm -rf dist
	@rm -rf callgrind.*

tags:
	@ctags -e -R -o TAGS

debug:
	gdb --command=.gdbdebug python

prof: build
	valgrind  --tool=callgrind --suppressions=valgrind-python.supp ${PYTHON} test_rbtree.py

release:
	@$(PYTHON) setup.py sdist
	@$(PYTHON) setup.py bdist_egg
	@echo Release ready, check dist/
